server.port: ${PORT:5005}

spring:
  datasource:
    url: ${DATABASE_URL}
  profiles:
    include: keycloak

aprun:
  runners:
  - Andrew
  - Penny
  database: postgres

corona:
  cors:
    generators:
    - domains:
      - "pennyguess.com"
      - "andrewandpenny.run"
      subdomains:
      - "www"
      - "api"
      rootdomain: true
      protocols:
      - "http"
      - "https"

logging.level:
  org.springframework: INFO
  com.andrewflbarnes: INFO
