spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres}

penny:
  web:
    allowedOrigins:
    - "*"

logging.level:
  com.andrewflbarnes: DEBUG
