spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres}

corona:
  cors:
    exact:
    - "*"

logging.level:
  com.andrewflbarnes: DEBUG

management.endpoints.web.exposure.include: "*"
